name: mock_reflectly
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  decorated_flutter: ^0.0.2
  flutter_svg: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.0.0
  build_runner: ^1.1.0
  ozzie: ^1.0.1
  kiwi_generator: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - fonts/
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Book.ttf
        - asset: fonts/Avenir-Heavy.ttf
          weight: 700
        - asset: fonts/Avenir-Light.ttf
          weight: 300
        - asset: fonts/Avenir-Medium.ttf
          weight: 500
    - family: ReflectlyIcons
      fonts:
        - asset: fonts/ReflectlyIcons.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700